# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-06 13:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_models', '0002_auto_20180512_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 6, 13, 21, 50, 105352)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 6, 13, 21, 50, 104854)),
        ),
    ]
